language: cpp
sudo: false
matrix:
  include:
    - os: osx
      compiler: clang
      script:
        - git submodule update --init --recursive
        - mkdir build
        - cd build
        - cmake ../
        - make -j 2
